### ISSUE TITLE
Properly store generated PlantUML images directly in Antora content folder instead of output directory.

### ISSUE THREAD

**Issue by eshepelyuk** [eshepelyuk/asciidoctor-plantuml.js#2]
This is a placeholder for [antora#189](https://gitlab.com/antora/antora/issues/189)

**Comment by mojavelinux** [comment]
Information is now available in https://gitlab.com/antora/antora/issues/189.

As I understand it, the chrome extension also needs to work with an in-memory file system. Perhaps the Chrome extension can provide a stub that mimics the context object in Antora so it can receive the generated diagram as a buffer as well. @Mogztter does that look feasible to you?

**Comment by stephenc** [comment]
See #30 for the hackiest of hacky hacks to try and get this to work!

**Comment by stephenc** [comment]
@mojavelinux any progress?

**Comment by eshepelyuk** [comment]
@stephenc honestly, I'll be unable to handle the issue myself and I can't merge your PR since it doesn't pass the tests.

I'm not ready just to create a solution without any additional tests and ensuring that all other platforms are not broken.

Definately help from @Mogztter and @mojavelinux is required to close this. Or maybe there're other volunteers interested to pick this up and provide complete solution.

**Comment by stephenc** [comment]
I’m java not ecmascript... I don’t have the active practice to take this any further. Hopefully Dan Allen will pick it up

**Comment by eshepelyuk** [comment]
Well, I'm JVM guy too :)

**Comment by Mogztter** [comment]
So the extension should use a Virtual File System instead instead of using `writeFileSync`.
My idea is to pass the VFS as an argument when the extension is registered:

```js
const asciidoctor = require('asciidoctor.js')()
const plantuml = require('asciidoctor-plantuml')

const vfs = {
  add: (image) => { /* do something with the virtual file */ }
}

plantuml.register(asciidoctor.Extensions, {vfs})
```

In Antora the registration will be:

```js
const vfs = (context) => ({
  add: (image) => {
    const { component, version, module } = context.file.src
    context.contentCatalog.addFile({
      contents: image.contents,
      src: {
        component,
        version,
        module,
        family: 'image',
        mediaType: image.mediaType,
        basename: image.basename,
        relative: image.relative
      }
    })
  },
  get: (path) => { /* returns a virtual file */ }
})

plantuml.register(asciidoctor.Extensions, {vfs: vfs(context)})
```

Interestingly #29 could also be solved with the introduction of a VFS:

```js
const vfs = {
  add: (image) => { /* do something with the virtual file */ },
  get: (path) => { /* returns a virtual file */ }
}
```

If the "context" or the Virtual File System is undefined, we could fallback to `writeFileSync` (to be backward compatible).

**Comment by mojavelinux** [comment]
I like the idea, though I wonder if we should build off the idea in isomorphic-git. See https://isomorphic-git.org/docs/en/plugin_fs.

**Comment by Mogztter** [comment]
@mojavelinux We could but the FS plugin in Isomorphic Git is async. It's not an issue with the `add` function since you could in theory add the image asynchronously but the `get` (or `readFile` in the FS plugin terminology) must be sync in our context.

**Comment by eshepelyuk** [comment]
I have to reopen this issue, since I believe the implementation in #42 doesn't resolve issue's initial goal.

The intention of this issue is to be kept open until there will be out-of-the-box solution for plugin to store images into `Antora` content folder, without hacking `:imagesoutdir:` (as I do now) or creating yet another extension to adapt to `Antora` ( as in  eshepelyuk/asciidoctor-plantuml-antora/pull/1)
